# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zachary Schmitz
title: Aspiring Programmer/Software Engineer
email: schmitzzr@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  schmitzzr
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: c_rodriguezm
linkedin_username: schmitzzr
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Linktree
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile-circle.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Zach and I'm an aspiring programmer and software engineer.  I have essentially become a jack-of-all-trades, so my 
  personal projects reflect that.  There are just so many different computer science topics that I just keep finding new projects to work on in many
  different fields.  I love learning, and I am willing to accept any help and ask many questions if it means I can learn better! 


  I am most passionate about: Game development, mobile app development, and other projects where I can show off my creativity.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: DrawPad Basic
        link: https://github.com/schmitzzr/DrawPadBasic
        # link_text: Project Website
        additional_links:
          - title:  DrawPad Basic Github
            icon: fab fa-github
            url: https://github.com/schmitzzr/DrawPadBasic
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is an R markdown file of my senior project. 
          This project used regression techniques and parameter estimation in order to fully build out a mathematical model of 3 Differential Equations that would predict and model public opinion polling. 
          Training and Testing Data was from the Gallop Polling Organizaiton.
          
          I created this project in **R Studio** using the **R programming language** and utilized packages such as **plotly**, **deSolve**, **ggplot2**, **plot3D**, and **rootSolve**.
          
      - layout: top-middle
        title: Stock Price Tracker Web App
        link: https://links.carlosrodriguezm.com/stockapp
        # link_text: Project Website
        additional_links:
          - title:  stockapp github
            icon: fab fa-github
            url: https://github.com/crodriguezm2016/Stock-App
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This web app allows a user to enter a stock ticker, choose the type of data they would like to pull (Daily, Weekly, Monthly, or Quarterly) and how far back they would like to pull data from.
          Once these are selected, data is pulled from Yahoo! Finance and graphs for the opening, high, low, and closing prices, as well as the volume of shares traded are displayed.
          
          I created this project in **VS Code** using **Python** and utilized packages such as **pandas** and **yfinance**.
          
      - layout: top-middle
        title: 2016 Election Data Visualization
        link: https://links.carlosrodriguezm.com/2016election
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This coding project takes voting data from the 2016 Presidential Election and creates a Choropleth map by county to show the percent of vote share that Hilary Clinton or Donald Trump received.
          FIPS and a GeoJSON file are used to determine the color and shade to mark each county area.
          
          I created this project in **Google Colab** using **Python** and **Jupyter Notebooks**, utilizing packages such as **pandas** and **plotly**.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TA/HR Data Analysis Intern
        link: motional.com
        # link_text: boringcompany.com
        sub_title: Motional
        caption: June 2021 - Present
        quote: >
          We're making driverless vehicles a safe, reliable, and accessible reality.
        description: | # this will include new lines to allow paragraphs
            At Motional, I specialized in providing data-driven reports to the Human Resource, Talent Acquisition, and Leadership teams. 
            I primarily used **Google Sheets** and **Microsoft Excel** to conduct analytics and regression models on recruiting data from **GreenHouse**. 
            I also used **Google Data Studio** to create beautiful automated dashboards which were regularly sent out to the heads of the Engineering departments.

      - layout: left
        title: Teacher's Assistant
        link: wallawalla.edu
        # link_text: boringcompany.com
        sub_title: Walla Walla University
        caption: September 2020 - Present
        description: | # this will include new lines to allow paragraphs
            As a Teacher's Assistant, I assisted **4** different professors in both the **Math** and **Business** departments at my university.
            I taught the lab component of the **Intro to Statistics** class to over **20** students each week. 
            I also provided constructive feedback on coursework to over **80** students each week and held review session before exams for classes such as **Probability & Statistics**, **Intro to Statistics**, the **Calculus** sequence, **Investments**, and **Economics**.

      - layout: left
        title: Peer Tutor
        link: wallawalla.edu
        # link_text: boringcompany.com
        sub_title: Walla Walla University
        caption: September 2019 - Present
        description: | # this will include new lines to allow paragraphs
            As a peer tutor, I became a **CRLA Level 1 Certified Peer Tutor**.
            I helped over **10** students each week, both in person and virtually over **Microsoft Teams** in areas such as **Statistics**, **Calculus**, **R Programming**, and **Differential Equations**.

      - layout: left
        title: Teacher and Assistant Dean
        link: https://www.vejlefjordskolen.dk/
        # link_text: boringcompany.com
        sub_title: Vejlefjordskolen
        caption: August 2018 - June 2019
        description: | # this will include new lines to allow paragraphs
            I moved to **Denmark** for a year to work as a **Teacher** and **Assistant Dean**. 
            During the day, I taught **Math**, English, **Computers**, and E-sports to over **30** students between **2nd** grade and **8th** grade.
            In the evenings, I would foster mentorships with the boarding students, tutor, and perform nightly checks for over **50** students. 
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Washington
        caption: March 2020 - August 2022
        sub_title: BS Computer Science and Systems (CSS)
        description: | # this will include new lines to allow paragraphs
          During my time in the CSS program at University of Washington, I developed a passion and greater understanding of the plethora of languages and applications of computer science.
          I made sure to always turn in quality work, and ended the program with a 3.89 GPA.
      - layout: left
        title: University of Washington
        caption: September 2015 - December 2017
        sub_title: BS Mathematics
        description: | # this will include new lines to allow paragraphs
          During my time at University of Washington, I developed a passion and greater understanding of the plethora of languages and applications of computer science.
          I made sure to always turn in quality work, and ended the program with a 3.74 GPA.

  - title: Skills and Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      My main skill set includes:
      - Math: My strongest areas are in **Statistics** and **Differential Equations**
      - Programming: **Java**, **Python**, **C#**, **JavaScript**, and **HTML/CSS** are my strong suits.
      - Data Analytics: I have extensive experience using **Google Sheets**, **Excel**, and **Google Data Studio**.
      - Remote Work: I am comfortable with **Microsoft Teams**, **Zoom**, **G-Suite**, **Slack**, and **Overleaf** for **LaTeX**.
      - Languages: My native language is English, I am somewhat conversational in Danish, and am at a beginner level with Spanish.

      The certifications that I currently hold are below and to view them, click [here](https://drive.google.com/drive/folders/1Cd9c9oaLP5R89Ge4Ch1LaYf0udIcNyBq?usp=sharing).
      - Learning **Java** by LinkedIn Learning
      - Learning **SQL** Programming by LinkedIn Learning
      - Learning **Excel**: Data Analysis by LinkedIn Learning
      - Learning **Google Data Studio** for Marketers by LinkedIn Learning
      - **Data Visualization** for Data Analysis and Analytics by LinkedIn Learning

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some more details about things I have been interested in lately:
      - Coffee: Currently enjoying a washed single origin from Ethiopia by Roseline
      - Gaming: Lately, I've been playing Gunfire Reborn and League of Legends
      - Learning: Teaching myself some machine learning concepts from freeCodeCamp
      - Math: Mathematical Modeling and Differential Equations have been top of my list lately
      - Backpacking: Still reminiscing about the Tour du Mont Blanc which I did back in summer of 2019, pics of my trip can be found [here](https://drive.google.com/drive/folders/1pDKwUIW73xAk_3IKdI7oeG6KVyAbrZWW?usp=sharing).
      - Traveling: I've visited over 20 countries and am super excited to visit even more! Some of my favorite cities are Copenhagen (I'm biased), Venice, and Prague.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
