# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zachary Schmitz
title: Aspiring Programmer/Software Engineer
email: schmitzzr@gmail.com
# website: https://github.com/schmitzzr/Portfolio

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  schmitzzr
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: c_rodriguezm
linkedin_username: schmitzzr
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Linktree
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile-circle.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Zach and I'm an aspiring programmer and software engineer.  I have essentially become a jack-of-all-trades, so my 
  personal projects reflect that.  There are just so many different computer science topics that I just keep finding new projects to work on in many
  different fields.  I love learning, and I am willing to accept any help and ask many questions if it means I can learn better! 


  I am most passionate about: Game development, mobile app development, and other projects where I can show off my creativity.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 7 Minute Workout
        link: https://drive.google.com/drive/folders/1PMfYYGC3zaYbKq32WzzRlaWddBHHd5a2?usp=share_link
        link_text: Project Screenshots
        additional_links:
          - title:  7 Minute Workout Github
            icon: fab fa-github
            url: https://github.com/schmitzzr/WorkoutApp
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This project is an Android 12 mobile application that leads the user on a twelve-step timed exercise, which can run on 99% of Android devices.
          This project also contains a feature to calculate BMI that can take either imperial or metric units of measurement.
          Any completed workouts are stored in a database by the date and time completed, which the user can view to see their progress.
          
          I created this project in **Android Studio** using the **Kotlin programming language** and 
          utilized packages such as **Room**, **coroutines**, **lifecycle**, and **speech**.
          
      - layout: top-middle
        title: DrawPad Basic
        link: https://drive.google.com/drive/folders/16bRsNaErxeAjGKZPogds7RqduzFqolfc?usp=share_link
        link_text: Project Screenshots
        additional_links:
          - title:  DrawPad Basic Github
            icon: fab fa-github
            url: https://github.com/schmitzzr/DrawPadBasic
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This project is an Android 12 mobile application where users can draw on a canvas, which can run on 99% of Android devices.
          I created a custom layout that contains features including a color palette, undo/redo buttons, and adjustable brush size.
          If external storage permissions are granted, users can choose to draw over their own photos and save their drawings to their devices.
          
          I created this project in **Android Studio** using the **Kotlin programming language** and 
          utilized packages such as **graphics**, **coroutines**, and **lifecycle**.
          
      - layout: top-middle
        title: Speedfall
        link: https://schmitzzr.github.io/WebGame/
        # link_text: Project Website
        additional_links:
          - title:  Speedfall Github
            icon: fab fa-github
            url: https://github.com/schmitzzr/WebGame/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I led an agile group of three to create a vertical platformer with custom sprites and animations, and it is playable from any computer web browser.
          This web game was developed using a custom game engine, allowing for increased developer customization.  
          We implemented a custom physics engine, level layouts, a title screen, platforms, obstacles, and a scoring system.
          
          I created this project in **VS Code** using **JavaScript** and **HTML**.
          
      - layout: top-middle
        title: Trivia Maze
        link: https://github.com/schmitzzr/TriviaMaze/
        # link_text: Project Website
#         additional_links:
#           - title:  Trivia Maze Github
#             icon: fab fa-github
#             url: https://github.com/schmitzzr/TriviaMaze/
        description: | # this will include new lines to allow paragraphs
          I led an agile team of 3 to develop a trivia skills game using a model-view-controller pattern and object-oriented programming.
          We designed a fully-functioning GUI from scratch with customizable maze size and the ability to save and reload progress.
          We created a database to store and access multiple-choice trivia questions randomly to improve replayability.  
          
          I created this project in **IntelliJ** using **Java** and **SQLite**, utilizing the **JavaFX** package.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sales Representative
        link: https://www.vectormarketing.com/
        # link_text: boringcompany.com
        sub_title: Vector Marketing
        caption: May 2018 - September 2018
#         quote: >
#           We're making driverless vehicles a safe, reliable, and accessible reality.
        description: | # this will include new lines to allow paragraphs
            At Vector Marketing, I set my own hours and scheduled my own appointments to sell Cutco cutlery both in-person and over the phone.
            During my time, I maintained a 95% closing ratio with in-person sales by effectively communicating and connecting with my customers.
            Due to my diligence, I earned a President’s Letter by selling over $10,000 of Cutco products over three months.

            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Washington
        link: https://drive.google.com/file/d/1Syw9DI184O27skcxLvr4OfpczRAapwrH/view?usp=share_link
        link_text: Official Transcript
        caption: March 2020 - August 2022
        sub_title: BS Computer Science and Systems (CSS)
        description: | # this will include new lines to allow paragraphs
          During my time in the CSS program at University of Washington, I developed a passion and greater understanding of the plethora of languages and applications of computer science.
          I worked with multiple teams to complete projects and assuming the position of leader in many of them.
          I made sure to lead by example and always turn in quality work, and I ended the program with a 3.89 GPA.
      - layout: left
        title: University of Washington
        caption: September 2015 - December 2017
        sub_title: BS Mathematics
        description: | # this will include new lines to allow paragraphs
          During my time in the Mathematics program University of Washington, I grew my understanding of mathematical concepts and analysis.
          I remained diligent throughout the program, and my efforts resulted in a 3.74 GPA.

  - title: Skills and Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      My main skill set includes:
      - Programming Languages: **Java**, **Python**, **Kotlin**, **JavaScript**, and **HTML/CSS** are my strong suits.
      - Programming Concepts: I am confident in **Algorithms**, **Data Structures**, and **Object-Oriented Programming**.
      - Developer Tools: **IntelliJ**, **PyCharm**, **Android Studio**, **VS Code**, and **Unity** are the programs I use the most.
      - Math: My strongest areas are in **Probability**, **Statistics** and **Differential Equations**
      - Remote Work: I am comfortable with **Zoom** and **Overleaf** for **LaTeX**.

      The certifications that I *currently hold* are below.
      - [Programming Foundations: Object-Oriented Design](https://drive.google.com/file/d/1kWpIOsG0RuzgImJoLpvKLowNx3n9c87z/view?usp=share_link) by LinkedIn Learning
      - [Introduction to C# with Unity](https://www.linkedin.com/learning/certificates/33cc70c44877baa30995406ecff2699383eebddd70c3f369e66e6a3c353d9ae5?u=67682169) by LinkedIn Learning
      - [Scientific Computing with Python](https://www.freecodecamp.org/certification/schmitzzr/scientific-computing-with-python-v7) by freeCodeCamp
      
      The certifications that I am *actively pursuing* are below.
      - [The Complete Android 12 & Kotlin Development Masterclass](https://www.udemy.com/share/101WYy3@MhR00aBTtdBS17zX1StSM0nAywdvaBre6lI_PXJ-6N0xERACVGS5c9bDTi0WAr2T0g==/) by Udemy (60% completion)
      - [Complete C# Unity Game Developer 2D](https://www.udemy.com/share/103J8C3@y4pTFklyo9eJhQL2Ed_86rFYXbziulcOwkKwb_p7Fo43u3bbK_QBAMKncDvkGUtJmg==/) by Udemy (40% completion)
      - [100 Days of Code: The Complete Python Pro Bootcamp for 2023](https://www.udemy.com/share/102JUu3@gBQXJu-PNEP9fUaqVVwGcFXuwBbeH-hdOqNV5ek0jXTYXNpPWwft4zI0lsVsXV89sw==/) by Udemy (35% completion) 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some more details about things I have been interested in lately:
      - Gaming: Lately, I've been playing Valheim and League of Legends.
      - Learning: Teaching myself Android Studio and the Unity Game Engine. I've also been learning C# as well as building upon my Python skills.
      - Cooking: Recently made a beef wellington for a New Years dinner.  Other recipes I like include chicken pot pie and various sushi rolls.
      - Traveling: My most recent trip was a Mediterranean cruise in 2019.  We started in Rome and stopped at Pompeii, Montenegro, Mykonos, and ended in Athens.
      - Sports: I've been playing pickleball with my friends in a backyard court for the past few years.  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
